version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: team03_frontend
    ports:
      - "20380:80"
    networks:
      - team03_network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: team03_backend
    ports:
      - "20302:20302"
    networks:
      - team03_network
    environment:
      - NODE_ENV=production

networks:
  team03_network:
    driver: bridge
